export { default as Home } from './Home';
export { default as Register } from './Register';
export { default as Recent } from './Recent';
export { default as User } from './User';
export { default as Tags } from './Tags';
export { default as UserPin } from './user/UserPin'; 
export { default as UserFollowing } from './user/UserFollowing'; 
export { default as Pin } from './Pin';
export { default as Users } from './Users';